name: 每周删除提交记录
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 删除提交记录
      run: |
        git config --global user.name "91xcode" 
        git config --global user.email example@example.com 
        git checkout --orphan new_branch
        git commit -m "[feature]:initial commit"
        git branch -D master
        git branch -m master
        git push -f origin master
